### Register
POST {{host}}/api/auth/register
Content-Type: application/json

{
  "name": "Thanh Tùng",
  "username": "thanhtung200ng",
  "password": "Thanhtung123@"
}

### Login

POST {{host}}/api/auth/login
Content-Type: application/json

{
  "username": "thanhtung200ng@gmail.com",
  "password": "Thanhtung123@"
}

### Create Vocabulary
POST {{host}}/api/vocabularies/create
Content-Type: application/json

{
  "word": "犬",
  "type": "kanji",
  "translation": "Chó",
  "example": {
    "sentence": "犬が好きです。",
    "translation": "Tôi thích chó."
  },
  "readings": {
    "on": ["けん"],
    "kun": ["いぬ"]
  },
  "level": 1,
  "description": "Từ này thường dùng để chỉ động vật."
}

### List Vocabularies
GET {{host}}/api/vocabularies?page=1&limit=10
Content-Type: application/json

### Update Vocabulary
< {%
    request.variables.set("id", '66ff93fbfd02ceab050f28f9')
%}
PUT {{host}}/api/vocabularies/{{id}}
Content-Type: application/json

{
  "word": "犬",
  "type": "kanji",
  "translation": "Chó",
  "example": {
    "sentence": "犬が好きです。",
    "translation": "Tôi thích chó."
  },
  "readings": {
    "on": [
      "けん"
    ],
    "kun": [
      "いぬ"
    ]
  },
  "level": 1,
  "description": "Từ này thường dùng để chỉ động vật."
}

### Delete Vocabulary
< {%
    request.variables.set("id", '66ff93fbfd02ceab050f28f9')
%}
DELETE {{host}}/api/vocabularies/{{id}}
Content-Type: application/json

### Create Tag
POST {{host}}/api/tags/create
Content-Type: application/json

{
  "key": "N5",
  "description": "Đây là trình độ sơ cấp 1, sẽ bắt đầu học từ bảng chữ cái Hiragana, Katakana và học những chữ hán đơn giản. Có thể đọc hiểu và nghe được thông tin trong các cụm từ, câu, đoạn văn dạng cố định viết bằng chữ hiragana, katakana và chữ hán cơ bản dùng trong sinh hoạt hàng ngày."
}